### ISSUE TITLE
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

### ISSUE THREAD

**Issue by guilinhu** [openPupil/PyPupilEXT#5]
I have been following the process of installing on a Mac M1 computer. However, when I run ```python setup.py sdist bdist_wheel ```, I get the following error message. This error appears again when I follow the "The advanced way of installing PyPupilEXT if nothing works" section and run ```cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=x64-osx -DCMAKE_TOOLCHAIN_FILE=3rdparty/vcpkg/scripts/buildsystems/vcpkg.cmake``` after I set the numpy C++ path. Any insights into the potential issue? Thanks!

```
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_gitlab.cmake:118 (vcpkg_download_distfile)
  buildtrees/versioning_/versions/tiff/b416d3e62450590e19a43f04b573c65555f3bc62/portfile.cmake:3 (vcpkg_from_gitlab)
  scripts/ports.cmake:147 (include)


error: building tiff:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tiff
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[tiff]+Build+error
Include '[tiff] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: e99d9a4fa 2022-08-18 (7 months ago)

You can also use the prefilled template from /Users/guilinhu/Documents/eye/PyPupilEXT/build/vcpkg_installed/vcpkg/issue_body.md.

-- Running vcpkg install - failed
CMake Error at 3rdparty/vcpkg/scripts/buildsystems/vcpkg.cmake:860 (message):
  vcpkg install failed.  See logs for more information:
  /Users/guilinhu/Documents/eye/PyPupilEXT/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.26.1/share/cmake/Modules/CMakeDetermineSystem.cmake:148 (include)
  CMakeLists.txt:21 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/Users/guilinhu/Documents/eye/PyPupilEXT/setup.py", line 108, in <module>
    setup(
  File "/Users/guilinhu/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/guilinhu/opt/anaconda3/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/guilinhu/opt/anaconda3/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/guilinhu/opt/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/guilinhu/opt/anaconda3/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/Users/guilinhu/opt/anaconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/guilinhu/opt/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/guilinhu/opt/anaconda3/lib/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Users/guilinhu/opt/anaconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/guilinhu/opt/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/guilinhu/Documents/eye/PyPupilEXT/setup.py", line 51, in run
    self.build_extension(ext)
  File "/Users/guilinhu/Documents/eye/PyPupilEXT/setup.py", line 91, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd='build/',
  File "/Users/guilinhu/opt/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/Users/guilinhu/Documents/eye/PyPupilEXT', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/guilinhu/Documents/eye/PyPupilEXT/build/lib.macosx-10.9-x86_64-3.9/pypupilext', '-DPYTHON_EXECUTABLE=/Users/guilinhu/opt/anaconda3/bin/python', '-DEXAMPLE_VERSION_INFO=0.0.1', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=3rdparty/vcpkg/scripts/buildsystems/vcpkg.cmake', '-DPython_NumPy_INCLUDE_DIR=/Users/guilinhu/opt/anaconda3/lib/python3.9/site-packages/numpy/core/include', '-DTBB_TEST=OFF', '-DTBBMALLOC_BUILD=OFF-DTBBMALLOC_PROXY_BUILD=OFF-DBUILD_SHARED_LIBS=OFF', '-DCMAKE_BUILD_TYPE=Release', '-DVCPKG_TARGET_TRIPLET=x64-osx']' returned non-zero exit status 1.
```

**Comment by BZandi** [comment]
The project has been updated, and the build process should now work smoothly on Windows, Ubuntu, and macOS. The instructions in the README file were revised accordingly.

Further, there are now prebuilt wheel files, so you no longer need to build the project from source if your primary goal is to use it. Here's a link to the wheel files for different platforms: https://github.com/openPupil/PyPupilEXT/releases/tag/v0.0.1-beta
